apiVersion: apps/v1
kind: Deployment
metadata:
  name: team-alpha-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: team-alpha
  template:
    metadata:
      labels:
        app: team-alpha
    spec:
      containers:
      - name: nginx
        image: nginx:1.23.3
        securityContext:
          privileged: false

